// Vocabulary bank used by generateLessons.js to programmatically build
// hundreds of reading/listening/speaking/writing/grammar lessons.
//
// Each noun is tagged with its grammatical gender (der/die/das) so the
// generator can build correct sentences (e.g. accusative "den Hund",
// dative "dem Hund") without needing hand-written sentences per word.
//
// To add more lessons: add more topics or more nouns per topic below.
// Nothing else needs to change — generateLessons.js picks up new entries
// automatically the next time the server starts.

function topic(id, title, nouns) {
  return { id, title, nouns };
}

const beginner = [
  topic("familie", "Familie", [
    { de: "Vater", en: "father", gender: "der" },
    { de: "Mutter", en: "mother", gender: "die" },
    { de: "Bruder", en: "brother", gender: "der" },
    { de: "Schwester", en: "sister", gender: "die" },
    { de: "Sohn", en: "son", gender: "der" },
    { de: "Tochter", en: "daughter", gender: "die" },
    { de: "Opa", en: "grandpa", gender: "der" },
    { de: "Oma", en: "grandma", gender: "die" },
    { de: "Onkel", en: "uncle", gender: "der" },
    { de: "Tante", en: "aunt", gender: "die" },
    { de: "Cousin", en: "cousin (male)", gender: "der" },
    { de: "Cousine", en: "cousin (female)", gender: "die" }
  ]),
  topic("tiere", "Tiere", [
    { de: "Hund", en: "dog", gender: "der" },
    { de: "Katze", en: "cat", gender: "die" },
    { de: "Vogel", en: "bird", gender: "der" },
    { de: "Maus", en: "mouse", gender: "die" },
    { de: "Pferd", en: "horse", gender: "das" },
    { de: "Kuh", en: "cow", gender: "die" },
    { de: "Schwein", en: "pig", gender: "das" },
    { de: "Fisch", en: "fish", gender: "der" },
    { de: "Löwe", en: "lion", gender: "der" },
    { de: "Bär", en: "bear", gender: "der" },
    { de: "Elefant", en: "elephant", gender: "der" },
    { de: "Kaninchen", en: "rabbit", gender: "das" }
  ]),
  topic("obst", "Obst", [
    { de: "Apfel", en: "apple", gender: "der" },
    { de: "Banane", en: "banana", gender: "die" },
    { de: "Orange", en: "orange", gender: "die" },
    { de: "Traube", en: "grape", gender: "die" },
    { de: "Erdbeere", en: "strawberry", gender: "die" },
    { de: "Kirsche", en: "cherry", gender: "die" },
    { de: "Birne", en: "pear", gender: "die" },
    { de: "Zitrone", en: "lemon", gender: "die" },
    { de: "Ananas", en: "pineapple", gender: "die" },
    { de: "Melone", en: "melon", gender: "die" },
    { de: "Pfirsich", en: "peach", gender: "der" },
    { de: "Pflaume", en: "plum", gender: "die" }
  ]),
  topic("gemuese", "Gemüse", [
    { de: "Kartoffel", en: "potato", gender: "die" },
    { de: "Tomate", en: "tomato", gender: "die" },
    { de: "Gurke", en: "cucumber", gender: "die" },
    { de: "Karotte", en: "carrot", gender: "die" },
    { de: "Salat", en: "lettuce", gender: "der" },
    { de: "Zwiebel", en: "onion", gender: "die" },
    { de: "Knoblauch", en: "garlic", gender: "der" },
    { de: "Kohl", en: "cabbage", gender: "der" },
    { de: "Paprika", en: "bell pepper", gender: "die" },
    { de: "Spinat", en: "spinach", gender: "der" },
    { de: "Bohne", en: "bean", gender: "die" },
    { de: "Erbse", en: "pea", gender: "die" }
  ]),
  topic("kleidung", "Kleidung", [
    { de: "Mantel", en: "coat", gender: "der" },
    { de: "Hose", en: "pants", gender: "die" },
    { de: "Hemd", en: "shirt", gender: "das" },
    { de: "Rock", en: "skirt", gender: "der" },
    { de: "Jacke", en: "jacket", gender: "die" },
    { de: "Schuh", en: "shoe", gender: "der" },
    { de: "Mütze", en: "cap", gender: "die" },
    { de: "Schal", en: "scarf", gender: "der" },
    { de: "Pullover", en: "sweater", gender: "der" },
    { de: "Kleid", en: "dress", gender: "das" },
    { de: "Socke", en: "sock", gender: "die" },
    { de: "Gürtel", en: "belt", gender: "der" }
  ]),
  topic("moebel", "Möbel", [
    { de: "Tisch", en: "table", gender: "der" },
    { de: "Stuhl", en: "chair", gender: "der" },
    { de: "Bett", en: "bed", gender: "das" },
    { de: "Schrank", en: "closet", gender: "der" },
    { de: "Sofa", en: "sofa", gender: "das" },
    { de: "Lampe", en: "lamp", gender: "die" },
    { de: "Spiegel", en: "mirror", gender: "der" },
    { de: "Regal", en: "shelf", gender: "das" },
    { de: "Teppich", en: "rug", gender: "der" },
    { de: "Tür", en: "door", gender: "die" },
    { de: "Fenster", en: "window", gender: "das" },
    { de: "Kissen", en: "pillow", gender: "das" }
  ]),
  topic("zimmer", "Zimmer im Haus", [
    { de: "Wohnzimmer", en: "living room", gender: "das" },
    { de: "Schlafzimmer", en: "bedroom", gender: "das" },
    { de: "Küche", en: "kitchen", gender: "die" },
    { de: "Badezimmer", en: "bathroom", gender: "das" },
    { de: "Flur", en: "hallway", gender: "der" },
    { de: "Keller", en: "basement", gender: "der" },
    { de: "Dachboden", en: "attic", gender: "der" },
    { de: "Esszimmer", en: "dining room", gender: "das" },
    { de: "Büro", en: "office", gender: "das" },
    { de: "Garten", en: "garden", gender: "der" },
    { de: "Garage", en: "garage", gender: "die" },
    { de: "Treppe", en: "staircase", gender: "die" }
  ]),
  topic("koerper", "Körperteile", [
    { de: "Kopf", en: "head", gender: "der" },
    { de: "Auge", en: "eye", gender: "das" },
    { de: "Nase", en: "nose", gender: "die" },
    { de: "Mund", en: "mouth", gender: "der" },
    { de: "Ohr", en: "ear", gender: "das" },
    { de: "Arm", en: "arm", gender: "der" },
    { de: "Hand", en: "hand", gender: "die" },
    { de: "Bein", en: "leg", gender: "das" },
    { de: "Fuß", en: "foot", gender: "der" },
    { de: "Finger", en: "finger", gender: "der" },
    { de: "Bauch", en: "belly", gender: "der" },
    { de: "Rücken", en: "back", gender: "der" }
  ]),
  topic("verkehr", "Verkehr", [
    { de: "Auto", en: "car", gender: "das" },
    { de: "Bus", en: "bus", gender: "der" },
    { de: "Zug", en: "train", gender: "der" },
    { de: "Fahrrad", en: "bicycle", gender: "das" },
    { de: "Flugzeug", en: "airplane", gender: "das" },
    { de: "Schiff", en: "ship", gender: "das" },
    { de: "U-Bahn", en: "subway", gender: "die" },
    { de: "Taxi", en: "taxi", gender: "das" },
    { de: "Motorrad", en: "motorcycle", gender: "das" },
    { de: "Straßenbahn", en: "tram", gender: "die" },
    { de: "Roller", en: "scooter", gender: "der" },
    { de: "Hubschrauber", en: "helicopter", gender: "der" }
  ]),
  topic("berufe", "Berufe", [
    { de: "Lehrer", en: "teacher (male)", gender: "der" },
    { de: "Ärztin", en: "doctor (female)", gender: "die" },
    { de: "Polizist", en: "police officer (male)", gender: "der" },
    { de: "Krankenschwester", en: "nurse", gender: "die" },
    { de: "Koch", en: "cook", gender: "der" },
    { de: "Verkäuferin", en: "salesperson (female)", gender: "die" },
    { de: "Ingenieur", en: "engineer", gender: "der" },
    { de: "Anwältin", en: "lawyer (female)", gender: "die" },
    { de: "Bäcker", en: "baker", gender: "der" },
    { de: "Friseurin", en: "hairdresser (female)", gender: "die" },
    { de: "Kellner", en: "waiter", gender: "der" },
    { de: "Sekretärin", en: "secretary (female)", gender: "die" }
  ]),
  topic("schule", "In der Schule", [
    { de: "Stift", en: "pen", gender: "der" },
    { de: "Buch", en: "book", gender: "das" },
    { de: "Tafel", en: "blackboard", gender: "die" },
    { de: "Rucksack", en: "backpack", gender: "der" },
    { de: "Heft", en: "notebook", gender: "das" },
    { de: "Bleistift", en: "pencil", gender: "der" },
    { de: "Schere", en: "scissors", gender: "die" },
    { de: "Kleber", en: "glue", gender: "der" },
    { de: "Lineal", en: "ruler", gender: "das" },
    { de: "Uhr", en: "clock", gender: "die" },
    { de: "Computer", en: "computer", gender: "der" },
    { de: "Papier", en: "paper", gender: "das" }
  ]),
  topic("natur", "Wetter und Natur", [
    { de: "Sonne", en: "sun", gender: "die" },
    { de: "Mond", en: "moon", gender: "der" },
    { de: "Stern", en: "star", gender: "der" },
    { de: "Wolke", en: "cloud", gender: "die" },
    { de: "Regen", en: "rain", gender: "der" },
    { de: "Schnee", en: "snow", gender: "der" },
    { de: "Wind", en: "wind", gender: "der" },
    { de: "Baum", en: "tree", gender: "der" },
    { de: "Blume", en: "flower", gender: "die" },
    { de: "Gras", en: "grass", gender: "das" },
    { de: "Berg", en: "mountain", gender: "der" },
    { de: "Fluss", en: "river", gender: "der" }
  ])
];

const intermediate = [
  topic("reisen", "Reisen", [
    { de: "Flughafen", en: "airport", gender: "der" },
    { de: "Hotel", en: "hotel", gender: "das" },
    { de: "Koffer", en: "suitcase", gender: "der" },
    { de: "Reisepass", en: "passport", gender: "der" },
    { de: "Grenze", en: "border", gender: "die" },
    { de: "Sehenswürdigkeit", en: "landmark", gender: "die" },
    { de: "Urlaub", en: "vacation", gender: "der" },
    { de: "Buchung", en: "booking", gender: "die" },
    { de: "Ticket", en: "ticket", gender: "das" },
    { de: "Zoll", en: "customs", gender: "der" },
    { de: "Unterkunft", en: "accommodation", gender: "die" },
    { de: "Tourist", en: "tourist", gender: "der" }
  ]),
  topic("restaurant", "Im Restaurant", [
    { de: "Speisekarte", en: "menu", gender: "die" },
    { de: "Rechnung", en: "bill", gender: "die" },
    { de: "Kellner", en: "waiter", gender: "der" },
    { de: "Vorspeise", en: "appetizer", gender: "die" },
    { de: "Hauptgericht", en: "main course", gender: "das" },
    { de: "Nachspeise", en: "dessert", gender: "die" },
    { de: "Trinkgeld", en: "tip", gender: "das" },
    { de: "Reservierung", en: "reservation", gender: "die" },
    { de: "Gastgeber", en: "host", gender: "der" },
    { de: "Serviette", en: "napkin", gender: "die" },
    { de: "Besteck", en: "cutlery", gender: "das" },
    { de: "Teller", en: "plate", gender: "der" }
  ]),
  topic("gesundheit", "Gesundheit", [
    { de: "Arzt", en: "doctor", gender: "der" },
    { de: "Apotheke", en: "pharmacy", gender: "die" },
    { de: "Medikament", en: "medication", gender: "das" },
    { de: "Krankheit", en: "illness", gender: "die" },
    { de: "Schmerz", en: "pain", gender: "der" },
    { de: "Verletzung", en: "injury", gender: "die" },
    { de: "Krankenhaus", en: "hospital", gender: "das" },
    { de: "Untersuchung", en: "examination", gender: "die" },
    { de: "Rezept", en: "prescription", gender: "das" },
    { de: "Behandlung", en: "treatment", gender: "die" },
    { de: "Impfung", en: "vaccination", gender: "die" },
    { de: "Notfall", en: "emergency", gender: "der" }
  ]),
  topic("technologie", "Technologie", [
    { de: "Computer", en: "computer", gender: "der" },
    { de: "Smartphone", en: "smartphone", gender: "das" },
    { de: "Software", en: "software", gender: "die" },
    { de: "Internet", en: "internet", gender: "das" },
    { de: "App", en: "app", gender: "die" },
    { de: "Passwort", en: "password", gender: "das" },
    { de: "Bildschirm", en: "screen", gender: "der" },
    { de: "Tastatur", en: "keyboard", gender: "die" },
    { de: "Datei", en: "file", gender: "die" },
    { de: "Akku", en: "battery", gender: "der" },
    { de: "Kamera", en: "camera", gender: "die" },
    { de: "Netzwerk", en: "network", gender: "das" }
  ]),
  topic("umwelt", "Umwelt", [
    { de: "Umwelt", en: "environment", gender: "die" },
    { de: "Müll", en: "trash", gender: "der" },
    { de: "Recycling", en: "recycling", gender: "das" },
    { de: "Verschmutzung", en: "pollution", gender: "die" },
    { de: "Energie", en: "energy", gender: "die" },
    { de: "Klimawandel", en: "climate change", gender: "der" },
    { de: "Erderwärmung", en: "global warming", gender: "die" },
    { de: "Wald", en: "forest", gender: "der" },
    { de: "Ökosystem", en: "ecosystem", gender: "das" },
    { de: "Nachhaltigkeit", en: "sustainability", gender: "die" },
    { de: "Ressource", en: "resource", gender: "die" },
    { de: "Luft", en: "air", gender: "die" }
  ]),
  topic("arbeit", "Arbeit und Karriere", [
    { de: "Chef", en: "boss", gender: "der" },
    { de: "Kollegin", en: "colleague (female)", gender: "die" },
    { de: "Gehalt", en: "salary", gender: "das" },
    { de: "Bewerbung", en: "job application", gender: "die" },
    { de: "Vertrag", en: "contract", gender: "der" },
    { de: "Besprechung", en: "meeting", gender: "die" },
    { de: "Aufgabe", en: "task", gender: "die" },
    { de: "Projekt", en: "project", gender: "das" },
    { de: "Erfahrung", en: "experience", gender: "die" },
    { de: "Qualifikation", en: "qualification", gender: "die" },
    { de: "Erfolg", en: "success", gender: "der" },
    { de: "Kündigung", en: "termination", gender: "die" }
  ]),
  topic("geld", "Geld und Bank", [
    { de: "Geld", en: "money", gender: "das" },
    { de: "Bank", en: "bank", gender: "die" },
    { de: "Konto", en: "account", gender: "das" },
    { de: "Kreditkarte", en: "credit card", gender: "die" },
    { de: "Steuer", en: "tax", gender: "die" },
    { de: "Kredit", en: "loan", gender: "der" },
    { de: "Ersparnis", en: "savings", gender: "die" },
    { de: "Investition", en: "investment", gender: "die" },
    { de: "Münze", en: "coin", gender: "die" },
    { de: "Geldschein", en: "banknote", gender: "der" },
    { de: "Gebühr", en: "fee", gender: "die" },
    { de: "Rechnung", en: "invoice", gender: "die" }
  ]),
  topic("bildung", "Bildung", [
    { de: "Schule", en: "school", gender: "die" },
    { de: "Universität", en: "university", gender: "die" },
    { de: "Student", en: "student", gender: "der" },
    { de: "Prüfung", en: "exam", gender: "die" },
    { de: "Zeugnis", en: "report card", gender: "das" },
    { de: "Unterricht", en: "class/lesson", gender: "der" },
    { de: "Vorlesung", en: "lecture", gender: "die" },
    { de: "Hausaufgabe", en: "homework", gender: "die" },
    { de: "Stipendium", en: "scholarship", gender: "das" },
    { de: "Bibliothek", en: "library", gender: "die" },
    { de: "Abschluss", en: "degree/graduation", gender: "der" },
    { de: "Note", en: "grade", gender: "die" }
  ]),
  topic("beziehungen", "Beziehungen", [
    { de: "Freund", en: "friend/boyfriend", gender: "der" },
    { de: "Freundin", en: "friend/girlfriend", gender: "die" },
    { de: "Ehe", en: "marriage", gender: "die" },
    { de: "Partner", en: "partner", gender: "der" },
    { de: "Freundschaft", en: "friendship", gender: "die" },
    { de: "Vertrauen", en: "trust", gender: "das" },
    { de: "Streit", en: "argument", gender: "der" },
    { de: "Versöhnung", en: "reconciliation", gender: "die" },
    { de: "Verabredung", en: "date/appointment", gender: "die" },
    { de: "Liebe", en: "love", gender: "die" },
    { de: "Respekt", en: "respect", gender: "der" },
    { de: "Kommunikation", en: "communication", gender: "die" }
  ]),
  topic("wohnen", "Wohnen", [
    { de: "Wohnung", en: "apartment", gender: "die" },
    { de: "Miete", en: "rent", gender: "die" },
    { de: "Vermieter", en: "landlord", gender: "der" },
    { de: "Mieter", en: "tenant", gender: "der" },
    { de: "Umzug", en: "move (relocation)", gender: "der" },
    { de: "Nebenkosten", en: "utility costs", gender: "die" },
    { de: "Balkon", en: "balcony", gender: "der" },
    { de: "Nachbarschaft", en: "neighborhood", gender: "die" },
    { de: "Aufzug", en: "elevator", gender: "der" },
    { de: "Kaution", en: "deposit", gender: "die" },
    { de: "Mietvertrag", en: "lease", gender: "der" },
    { de: "Renovierung", en: "renovation", gender: "die" }
  ]),
  topic("kultur", "Kultur und Traditionen", [
    { de: "Fest", en: "festival", gender: "das" },
    { de: "Tradition", en: "tradition", gender: "die" },
    { de: "Feiertag", en: "holiday", gender: "der" },
    { de: "Museum", en: "museum", gender: "das" },
    { de: "Kunst", en: "art", gender: "die" },
    { de: "Musik", en: "music", gender: "die" },
    { de: "Tanz", en: "dance", gender: "der" },
    { de: "Theater", en: "theater", gender: "das" },
    { de: "Ausstellung", en: "exhibition", gender: "die" },
    { de: "Denkmal", en: "monument", gender: "das" },
    { de: "Geschichte", en: "history/story", gender: "die" },
    { de: "Brauch", en: "custom", gender: "der" }
  ])
];

const advanced = [
  topic("politik", "Politik", [
    { de: "Regierung", en: "government", gender: "die" },
    { de: "Staat", en: "state", gender: "der" },
    { de: "Gesetz", en: "law", gender: "das" },
    { de: "Wahl", en: "election", gender: "die" },
    { de: "Partei", en: "party (political)", gender: "die" },
    { de: "Politiker", en: "politician", gender: "der" },
    { de: "Demokratie", en: "democracy", gender: "die" },
    { de: "Verfassung", en: "constitution", gender: "die" },
    { de: "Opposition", en: "opposition", gender: "die" },
    { de: "Reform", en: "reform", gender: "die" },
    { de: "Diplomatie", en: "diplomacy", gender: "die" },
    { de: "Bürger", en: "citizen", gender: "der" }
  ]),
  topic("wirtschaft", "Wirtschaft", [
    { de: "Wirtschaft", en: "economy", gender: "die" },
    { de: "Markt", en: "market", gender: "der" },
    { de: "Unternehmen", en: "company", gender: "das" },
    { de: "Inflation", en: "inflation", gender: "die" },
    { de: "Nachfrage", en: "demand", gender: "die" },
    { de: "Angebot", en: "supply/offer", gender: "das" },
    { de: "Wettbewerb", en: "competition", gender: "der" },
    { de: "Produktion", en: "production", gender: "die" },
    { de: "Export", en: "export", gender: "der" },
    { de: "Import", en: "import", gender: "der" },
    { de: "Rezession", en: "recession", gender: "die" },
    { de: "Wohlstand", en: "prosperity", gender: "der" }
  ]),
  topic("wissenschaft", "Wissenschaft und Forschung", [
    { de: "Forschung", en: "research", gender: "die" },
    { de: "Experiment", en: "experiment", gender: "das" },
    { de: "Theorie", en: "theory", gender: "die" },
    { de: "Hypothese", en: "hypothesis", gender: "die" },
    { de: "Studie", en: "study", gender: "die" },
    { de: "Ergebnis", en: "result", gender: "das" },
    { de: "Universität", en: "university", gender: "die" },
    { de: "Wissenschaftler", en: "scientist", gender: "der" },
    { de: "Entdeckung", en: "discovery", gender: "die" },
    { de: "Innovation", en: "innovation", gender: "die" },
    { de: "Technologie", en: "technology", gender: "die" },
    { de: "Analyse", en: "analysis", gender: "die" }
  ]),
  topic("philosophie", "Philosophie und Ethik", [
    { de: "Ethik", en: "ethics", gender: "die" },
    { de: "Moral", en: "morality", gender: "die" },
    { de: "Gerechtigkeit", en: "justice", gender: "die" },
    { de: "Freiheit", en: "freedom", gender: "die" },
    { de: "Wahrheit", en: "truth", gender: "die" },
    { de: "Bewusstsein", en: "consciousness", gender: "das" },
    { de: "Verantwortung", en: "responsibility", gender: "die" },
    { de: "Wert", en: "value", gender: "der" },
    { de: "Pflicht", en: "duty", gender: "die" },
    { de: "Prinzip", en: "principle", gender: "das" },
    { de: "Vernunft", en: "reason", gender: "die" },
    { de: "Existenz", en: "existence", gender: "die" }
  ]),
  topic("geschichte", "Geschichte", [
    { de: "Geschichte", en: "history", gender: "die" },
    { de: "Krieg", en: "war", gender: "der" },
    { de: "Frieden", en: "peace", gender: "der" },
    { de: "Revolution", en: "revolution", gender: "die" },
    { de: "Reich", en: "empire", gender: "das" },
    { de: "Kolonie", en: "colony", gender: "die" },
    { de: "Diktatur", en: "dictatorship", gender: "die" },
    { de: "Widerstand", en: "resistance", gender: "der" },
    { de: "Erinnerung", en: "memory", gender: "die" },
    { de: "Denkmal", en: "monument", gender: "das" },
    { de: "Epoche", en: "era", gender: "die" },
    { de: "Vertrag", en: "treaty", gender: "der" }
  ]),
  topic("literatur", "Literatur und Kunst", [
    { de: "Roman", en: "novel", gender: "der" },
    { de: "Gedicht", en: "poem", gender: "das" },
    { de: "Autor", en: "author", gender: "der" },
    { de: "Erzählung", en: "narrative", gender: "die" },
    { de: "Charakter", en: "character", gender: "der" },
    { de: "Handlung", en: "plot", gender: "die" },
    { de: "Stil", en: "style", gender: "der" },
    { de: "Metapher", en: "metaphor", gender: "die" },
    { de: "Kapitel", en: "chapter", gender: "das" },
    { de: "Kritik", en: "criticism/review", gender: "die" },
    { de: "Meisterwerk", en: "masterpiece", gender: "das" },
    { de: "Interpretation", en: "interpretation", gender: "die" }
  ]),
  topic("psychologie", "Psychologie", [
    { de: "Psyche", en: "psyche", gender: "die" },
    { de: "Verhalten", en: "behavior", gender: "das" },
    { de: "Emotion", en: "emotion", gender: "die" },
    { de: "Wahrnehmung", en: "perception", gender: "die" },
    { de: "Gedächtnis", en: "memory (faculty)", gender: "das" },
    { de: "Motivation", en: "motivation", gender: "die" },
    { de: "Stress", en: "stress", gender: "der" },
    { de: "Angst", en: "fear/anxiety", gender: "die" },
    { de: "Selbstbewusstsein", en: "self-confidence", gender: "das" },
    { de: "Persönlichkeit", en: "personality", gender: "die" },
    { de: "Therapie", en: "therapy", gender: "die" },
    { de: "Trauma", en: "trauma", gender: "das" }
  ]),
  topic("globalisierung", "Globalisierung", [
    { de: "Globalisierung", en: "globalization", gender: "die" },
    { de: "Handel", en: "trade", gender: "der" },
    { de: "Migration", en: "migration", gender: "die" },
    { de: "Kultur", en: "culture", gender: "die" },
    { de: "Vielfalt", en: "diversity", gender: "die" },
    { de: "Zusammenarbeit", en: "cooperation", gender: "die" },
    { de: "Abhängigkeit", en: "dependency", gender: "die" },
    { de: "Einfluss", en: "influence", gender: "der" },
    { de: "Grenze", en: "border", gender: "die" },
    { de: "Integration", en: "integration", gender: "die" },
    { de: "Austausch", en: "exchange", gender: "der" },
    { de: "Verflechtung", en: "interconnection", gender: "die" }
  ]),
  topic("recht", "Recht und Justiz", [
    { de: "Recht", en: "law/right", gender: "das" },
    { de: "Gericht", en: "court", gender: "das" },
    { de: "Richter", en: "judge", gender: "der" },
    { de: "Anwalt", en: "lawyer", gender: "der" },
    { de: "Urteil", en: "verdict", gender: "das" },
    { de: "Klage", en: "lawsuit", gender: "die" },
    { de: "Vertrag", en: "contract", gender: "der" },
    { de: "Verbrechen", en: "crime", gender: "das" },
    { de: "Strafe", en: "punishment", gender: "die" },
    { de: "Gerechtigkeit", en: "justice", gender: "die" },
    { de: "Zeuge", en: "witness", gender: "der" },
    { de: "Verhandlung", en: "trial/negotiation", gender: "die" }
  ]),
  topic("gesundheitssystem", "Gesundheitssystem", [
    { de: "Gesundheitssystem", en: "healthcare system", gender: "das" },
    { de: "Versicherung", en: "insurance", gender: "die" },
    { de: "Prävention", en: "prevention", gender: "die" },
    { de: "Diagnose", en: "diagnosis", gender: "die" },
    { de: "Therapie", en: "therapy", gender: "die" },
    { de: "Pflege", en: "care", gender: "die" },
    { de: "Personal", en: "staff", gender: "das" },
    { de: "Kapazität", en: "capacity", gender: "die" },
    { de: "Reform", en: "reform", gender: "die" },
    { de: "Zugang", en: "access", gender: "der" },
    { de: "Versorgung", en: "provision/care supply", gender: "die" },
    { de: "Epidemie", en: "epidemic", gender: "die" }
  ]),
  topic("gesellschaft", "Gesellschaft und Soziales", [
    { de: "Gesellschaft", en: "society", gender: "die" },
    { de: "Ungleichheit", en: "inequality", gender: "die" },
    { de: "Armut", en: "poverty", gender: "die" },
    { de: "Wohlstand", en: "prosperity", gender: "der" },
    { de: "Solidarität", en: "solidarity", gender: "die" },
    { de: "Integration", en: "integration", gender: "die" },
    { de: "Generation", en: "generation", gender: "die" },
    { de: "Wandel", en: "change/transformation", gender: "der" },
    { de: "Norm", en: "norm", gender: "die" },
    { de: "Identität", en: "identity", gender: "die" },
    { de: "Minderheit", en: "minority", gender: "die" },
    { de: "Zusammenhalt", en: "cohesion", gender: "der" }
  ]),
  topic("digital", "Digitale Gesellschaft", [
    { de: "Digitalisierung", en: "digitalization", gender: "die" },
    { de: "Algorithmus", en: "algorithm", gender: "der" },
    { de: "Automatisierung", en: "automation", gender: "die" },
    { de: "Überwachung", en: "surveillance", gender: "die" },
    { de: "Plattform", en: "platform", gender: "die" },
    { de: "Netzwerk", en: "network", gender: "das" },
    { de: "Sicherheit", en: "security", gender: "die" },
    { de: "Anonymität", en: "anonymity", gender: "die" },
    { de: "Fortschritt", en: "progress", gender: "der" },
    { de: "Datenschutz", en: "data protection", gender: "der" },
    { de: "KI", en: "AI", gender: "die" },
    { de: "Cyberkriminalität", en: "cybercrime", gender: "die" }
  ])
];

module.exports = { beginner, intermediate, advanced };
